version: '2'

services:
        redis:
                image: redis:3
                volumes:
                - ${PWD}/tmp/data:/data
                ports:
                - "6379"
                container_name: "redis-mosq"
                networks:
                - mosqnet

        mosquitto:
                build: .
                volumes:
                - ${PWD}/auth-plugin.conf:/etc/mosquitto.d/auth-plugin.conf
                ports:
                - "1883:1883"
                - "9883:9883"
                environment:
                - DOMAIN=example.local
                - PORT=8080
                networks:
                - mosqnet
                depends_on:
                - redis
                labels:
                - "local.example.description=Mosquitto v1.4.12 MQTT server"
#                links:
#                - redis:mosquitto.redis.link

networks:
        mosqnet:
